/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "buzz_gpio.h"
#include "buzz_rcc.h"
#include "buzz_systick.h"
//#include "i2c_scanner.h"
#include "buzz_i2c.h"
#include "buzz_usart.h"
#include "mpu6050.h"


int main(void)
{




}
